---
# defaults file for default-tooling

extend_packages: []

packages:
  # Shells & config
  - dnf: dnf-plugins-core
  - dnf: util-linux-user
  - dnf: zsh

  # Shell utils
  - dnf: vim
  - dnf: git
  - dnf: ansible
  - dnf: thefuck
  - dnf: stow

  # Desktop utils
  - dnf: tilix
  - dnf: tilix-nautilus
  - dnf: remmina
  - dnf: gthumb
  - dnf: vlc
  - dnf: libaacs
  - dnf: thunderbird
  - dnf: thunderbird-enigmail
  - dnf: pdfshuffler
  - dnf: virt-manager
  - dnf: virt-viewer
  - dnf: telegram-desktop
  - dnf: flatpak

  # Browsers
  - dnf: firefox
  - dnf: chromium

  # Passwordsaves
  - dnf: keepass
  - dnf: pass

  # Fonts
  - dnf: open-sans-fonts
  - dnf: fontawesome-fonts
  - dnf: fontawesome-fonts-web

