---
# tasks file for vscode
#

# Temporary fix.until 2.4.2 is provided
# See https://github.com/ansible/ansible/issues/32053
- name: Downgrade urllib3 to 1.13.1
  pip: 
    name: urllib3
    version: 1.13.1
  tags:
    - vscode
    - pip
    - libs
  become: true
  when:
    - ansible_version.major == 2
    - ansible_version.minor <= 4
    - ansible_version.revision < 2

- name: Import GPG key
  rpm_key:
    state: present
    key: "https://packages.microsoft.com/keys/microsoft.asc"
  tags:
    - vscode
    - dnf
    - gpg-key
    - download
  become: true

- name: Add official repository
  yum_repository:
    state: present
    name: vscode
    description: Official repository for VSCode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  tags:
    - vscode
    - dnf
    - gpg-key
  become: true

- name: Install vscode
  dnf:
    name: code
    state: present
  tags:
    - vscode
    - dnf
    - packages
  become: true

- name: Install Nautilus-Extension
  copy:
    src: open-code.py
    dest: /usr/share/nautilus-python/extensions/open-code.py
  tags:
    - vscode
    - python
    - nautilus
    - nautilus-python
    - nautlius-python-extension
  become: true
  notify: "Nautilus python extension notification"
