---
# tasks file for surface

- name: Install SELinux dependencies
  dnf:
    name: libselinux-python
    state: present
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_major_version > 21
    - ansible_selinux_python_present == false
  become: true

- stat: path=/etc/NetworkManager/conf.d/
  register: networkmanager_confd

- name: Disable Network manager MAC randomization on Surface
  template:
    src: networkmanager.conf
    dest: /etc/NetworkManager/conf.d/zz_surface.conf
  tags:
    - networkmanager
    - hardware
    - surface
  when:
    - networkmanager_confd.stat.exists == true
  notify:
    - restart NetworkManager
  become: true
