galaxy_info:
  author: Christoph Kern
  description: Installs default tooling for Fedora Setup

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  issue_tracker_url: https://github.com/SISheogorath/ansible-client/issues

  license: GPLv3

  min_ansible_version: 1.2

  #
  # platforms is a list of platforms, and each platform has a name and a list of versions.
  #
   platforms:
   - name: Fedora
     versions:
     - all

  galaxy_tags: []
dependencies: []
